<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Admin.aspx.cs" Inherits="Default2" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>HospitalDB - Admin View</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        Admin Tools<br />
        <br />
                Add/Edit/Remove Employeee<br />
        <br />
    
        <asp:TextBox ID="txtEmpName" runat="server">Employee Name</asp:TextBox>
        <asp:DropDownList ID="jobList" runat="server">
            <asp:ListItem>Doctor</asp:ListItem>
            <asp:ListItem>Legal</asp:ListItem>
            <asp:ListItem>Finance</asp:ListItem>
            <asp:ListItem>Staff</asp:ListItem>
        </asp:DropDownList>
        <asp:TextBox ID="txtEmpPass" runat="server">Employee Password</asp:TextBox>
        <asp:Button ID="btnAddEmp" runat="server" Text="Add New Employee" 
            onclick="btnAddEmp_Click" />
    
        <hr />
    
    </div>
    <asp:GridView ID="empGrid" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataSourceID="employeeData" 
        onrowdeleting="empGrid_RowDeleting" DataKeyNames="EmployeeID">
    </asp:GridView>
    <asp:SqlDataSource ID="employeeData" runat="server" 
        ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
        SelectCommand="SELECT * FROM EMPLOYEES" onupdated="employeeData_Updated"
        DeleteCommand="DELETE FROM employees WHERE EmployeeID = @EmployeeID"
        UpdateCommand="UPDATE employees SET EmployeeName=@EmployeeName, Job=@Job, Passwd=@Passwd WHERE EmployeeID=@EmployeeID"
        InsertCommand="INSERT INTO employees (EmployeeName, Job, Passwd) VALUES (@EmployeeName, @Job, @Passwd)">
        <InsertParameters>
            <asp:ControlParameter Name="EmployeeName" ControlID="txtEmpName" PropertyName="Text" />
            <asp:ControlParameter Name="Job" ControlID="jobList" PropertyName="SelectedValue" />
            <asp:ControlParameter Name="Passwd" ControlID="txtEmpPass" PropertyName="Text" />
        </InsertParameters>
        <DeleteParameters>
            <asp:SessionParameter SessionField="EmployeeID" Name="EmployeeID"  />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="empGrid" PropertyName="SelectedRow.Cells[1].Text" Name="EmployeeName" Type="String" />
            <asp:ControlParameter ControlID="empGrid" PropertyName="SelectedRow.Cells[2].Text" Name="Job" Type="String" />
            <asp:ControlParameter ControlID="empGrid" PropertyName="SelectedRow.Cells[3].Text" Name="Passwd" Type="String" />
        </UpdateParameters>
        </asp:SqlDataSource>
    
        <hr />
    
    <br />
    Add/Edit and Remove Patients<br />
    <br />
    
    <asp:TextBox ID="patientName" runat="server">Patient Name</asp:TextBox>
    <asp:TextBox ID="txtAddress" runat="server">Address</asp:TextBox>
    <asp:TextBox ID="txtPhone" runat="server">Phone Number</asp:TextBox>
    <asp:TextBox ID="txtHealthCard" runat="server">Health Card</asp:TextBox>
    <asp:TextBox ID="txtSIN" runat="server">SIN Number</asp:TextBox>
    <asp:TextBox ID="txtPatientPass" runat="server">Password</asp:TextBox>
    <asp:DropDownList ID="listDoctor" runat="server" DataSourceID="docSource" 
        DataTextField="EmployeeName" DataValueField="EmployeeID">
        <asp:ListItem Value="0">Doctor</asp:ListItem>
    </asp:DropDownList>
    <asp:TextBox ID="txtStatus" runat="server">Status</asp:TextBox>
    <asp:Button ID="btnAddPatient" runat="server" Text="Add Patient" 
        onclick="btnAddPatient_Click" />
    
        <hr />
    
    <asp:GridView ID="patientGrid" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataSourceID="patientData" 
        onrowdeleting="patientGrid_RowDeleting" DataKeyNames="PatientID">
    </asp:GridView>
    <asp:SqlDataSource ID="patientData" runat="server" 
        ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
        SelectCommand="SELECT * FROM patients"
        DeleteCommand="DELETE FROM patients WHERE PatientID = @PatientID"
        UpdateCommand="UPDATE patients SET PatientName=@PatientName, Address=@Address,PhoneNum=@PhoneNum,HealthCardNum=@HealthCardNum,SIN=@SIN,Password=@Password,NumVisits=@NumVisits,Doctor=@Doctor,Status=@Status WHERE PatientID=@PatientID"
        InsertCommand="INSERT INTO patients (PatientName, Address, PhoneNum, HealthCardNum, SIN, Password, Doctor, Status) VALUES (@PatientName, @Address, @PhoneNum, @HealthCardNum, @SIN, @Password, @Doctor, @Status )" 
        onupdated="patientData_Updated">
        <InsertParameters>
            <asp:ControlParameter Name="PatientName" ControlID="patientName" PropertyName="Text" />
            <asp:ControlParameter Name="Address" ControlID="txtAddress" PropertyName="Text" />
            <asp:ControlParameter Name="PhoneNum" ControlID="txtPhone" PropertyName="Text" />
            <asp:ControlParameter Name="HealthCardNum" ControlID="txtHealthCard" PropertyName="Text" />
            <asp:ControlParameter Name="SIN" ControlID="txtSIN" PropertyName="Text" />
            <asp:ControlParameter Name="Password" ControlID="txtPatientPass" PropertyName="Text" />
            <asp:ControlParameter Name="Doctor" ControlID="listDoctor" PropertyName="SelectedValue" />
            <asp:ControlParameter Name="Status" ControlID="txtStatus" PropertyName="Text" />
        </InsertParameters>
        <DeleteParameters>
            <asp:SessionParameter SessionField="PatientID"  Name="PatientID" />
        </DeleteParameters>
          <UpdateParameters>
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[0].Text" Name="PatientID" Type="UInt32" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[1].Text" Name="PatientName" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[2].Text" Name="Address" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[3].Text" Name="PhoneNum" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[4].Text" Name="HealthCardNum" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[5].Text" Name="SIN" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[6].Text" Name="Password" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[7].Text" Name="NumVisits" Type="UInt32" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[8].Text" Name="Doctor" Type="UInt32" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[9].Text" Name="Status" Type="UInt32" />
        </UpdateParameters>
        </asp:SqlDataSource>
    <asp:SqlDataSource ID="docSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
        SelectCommand="SELECT EmployeeID, EmployeeName FROM employees WHERE (Job = 'Doctor')">
    </asp:SqlDataSource>
    <br />
    </form>
</body>
</html>
