<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Staff.aspx.cs" Inherits="Staff" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>HospitalDB - Staff View</title>
    <style type="text/css">
        .style1
        {
            font-weight: bold;
            text-decoration: underline;
            color: #000099;
        }
        .style2
        {
            width: 331px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <p class="style1">
        <asp:SqlDataSource ID="PatNums" runat="server" 
            ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
            ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
            SelectCommand="SELECT PatientID,PatientName FROM patients"></asp:SqlDataSource>
        <asp:SqlDataSource ID="DocNums" runat="server" 
            ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
            ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
            SelectCommand="Select EmployeeID,EmployeeName from employees WHERE Job='Doctor'">
        </asp:SqlDataSource>
        Hospital Database</p>
    <div>
    
        <asp:Label ID="Label1" runat="server"></asp:Label>
        <br />
    
    </div>
    <asp:Label ID="Label2" runat="server" Text="Patient"></asp:Label>
    <asp:DropDownList ID="PatNum" runat="server" DataSourceID="PatNums" 
        DataTextField="PatientName" DataValueField="PatientID">
    </asp:DropDownList>
    <asp:Label ID="Label3" runat="server" Text="Doctor"></asp:Label>
    <asp:DropDownList ID="DocNum" runat="server" DataSourceID="DocNums" 
        DataTextField="EmployeeName" DataValueField="EmployeeID">
    </asp:DropDownList>
    <br />
    
        <hr />
    
    <br />
    <table style="width:100%;">
        <tr>
            <td class="style2">
    <asp:Calendar ID="AppointmentCal" runat="server" Caption="Start Date" 
        onselectionchanged="AppointmentCal_SelectionChanged"></asp:Calendar>
    <asp:DropDownList ID="StartHour" runat="server">
    </asp:DropDownList>
    <asp:DropDownList ID="StartMin" runat="server">
    </asp:DropDownList>
    <asp:DropDownList ID="StartAmPm" runat="server">
    </asp:DropDownList>
            </td>
            <td>
    <asp:Calendar ID="AppointmentCalEnd" runat="server" Caption="End Date">
    </asp:Calendar>
    <asp:DropDownList ID="EndHour" runat="server">
    </asp:DropDownList>
    <asp:DropDownList ID="EndMin" runat="server">
    </asp:DropDownList>
    <asp:DropDownList ID="EndAmPm" runat="server">
    </asp:DropDownList>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <asp:TextBox ID="CommentsBox" runat="server" Height="115px" 
        TextMode="MultiLine" Width="606px">Comments</asp:TextBox>
        <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
        Text="Book Appointment" Height="92px" />
            </td>
        </tr>
    </table>
    <br />
    <hr />
    <p>
        <asp:Button ID="AppointmentsBut" runat="server" onclick="AppointmentsBut_Click" 
            Text="Edit Appointments" />
    </p>
    <asp:GridView ID="AppointmentView" runat="server" DataKeyNames="VisitID" 
        DataSourceID="AppointmentData" Visible="False" 
        AutoGenerateEditButton="True" onrowediting="AppointmentView_RowEditing" 
        AutoGenerateDeleteButton="True" 
        onrowdeleting="AppointmentView_RowDeleting" 
        onrowupdating="AppointmentView_RowUpdating">
    </asp:GridView>
    <asp:SqlDataSource ID="AppointmentData" runat="server"
        UpdateCommand="UPDATE visits SET visits.StartDate=@StartDate,visits.EndDate=@EndDate,visits.Comments=@Comments WHERE VisitID=@VisitID"
        SelectCommand="SELECT VisitID,StartDate,EndDate,Comments FROM visits WHERE StartDate >= @NowDate" 
        DeleteCommand="DELETE FROM visits WHERE visitID=@DeletingVisit"
        ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" >
        <UpdateParameters>
            <asp:SessionParameter Name="StartDate" SessionField="newStaffStartDate" Type="DateTime"/>
            <asp:SessionParameter Name="EndDate" SessionField="newStaffEndDate" Type="DateTime"/>
            <asp:ControlParameter Name="Comments"  ControlID="AppointmentView" PropertyName="SelectedRow.Cells[3].Text" />
        </UpdateParameters>
        <SelectParameters>
            <asp:SessionParameter Name="NowDate" SessionField="NowDate" Type="DateTime" />
        </SelectParameters>
        <DeleteParameters>
            <asp:SessionParameter Name="DeletingVisit" SessionField="DeletingVisit" />
        </DeleteParameters>
    </asp:SqlDataSource>
    <br />
    <hr />
    <br />
    
    <asp:TextBox ID="patientName" runat="server">Patient Name</asp:TextBox>
    <asp:TextBox ID="txtAddress" runat="server">Address</asp:TextBox>
    <asp:TextBox ID="txtPhone" runat="server">Phone Number</asp:TextBox>
    <asp:TextBox ID="txtHealthCard" runat="server">Health Card</asp:TextBox>
    <asp:TextBox ID="txtSIN" runat="server">SIN Number</asp:TextBox>
    <asp:TextBox ID="txtPatientPass" runat="server">Password</asp:TextBox>
    <asp:DropDownList ID="listDoctor" runat="server" DataSourceID="docSource" 
        DataTextField="EmployeeName" DataValueField="EmployeeID">
        <asp:ListItem Value="0">Doctor</asp:ListItem>
    </asp:DropDownList>
    <asp:Button ID="btnAddPatient" runat="server" Text="Add Patient" 
        onclick="btnAddPatient_Click" />
    
        <br />
    <asp:TextBox ID="txtStatus" runat="server" Height="79px" 
        style="margin-top: 0px" TextMode="MultiLine" Width="856px">Status</asp:TextBox>    
    <br />
    
    <asp:GridView ID="patientGrid" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataSourceID="patientData" DataKeyNames="PatientID" 
        onrowupdating="patientGrid_RowUpdating">
    </asp:GridView>
    <br />
    <asp:SqlDataSource ID="docSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
        SelectCommand="SELECT EmployeeID, EmployeeName FROM employees WHERE (Job = 'Doctor')">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="patientData" runat="server" 
        ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
        SelectCommand="SELECT PatientID,PatientName,Address,PhoneNum,HealthCardNum,SIN, Password,(SELECT COUNT(*) FROM visits as v WHERE v.PatientID=p.PatientID) as NumVisits,Doctor,Status FROM patients as p" 
        DeleteCommand="DELETE FROM patients WHERE PatientID = @PatientID"
        UpdateCommand="UPDATE patients SET PatientName=@PatientName, Address=@Address,PhoneNum=@PhoneNum,HealthCardNum=@HealthCardNum,SIN=@SIN,Password=@Password,NumVisits=@NumVisits,Doctor=@Doctor,Status=@Status WHERE PatientID=@PatientID"
        InsertCommand="INSERT INTO patients (PatientName, Address, PhoneNum, HealthCardNum, SIN, Password, Doctor, Status) VALUES (@PatientName, @Address, @PhoneNum, @HealthCardNum, @SIN, @Password, @Doctor, @Status )" 
        onupdated="patientData_Updated">
        <InsertParameters>
            <asp:ControlParameter Name="PatientName" ControlID="patientName" PropertyName="Text" />
            <asp:ControlParameter Name="Address" ControlID="txtAddress" PropertyName="Text" />
            <asp:ControlParameter Name="PhoneNum" ControlID="txtPhone" PropertyName="Text" />
            <asp:ControlParameter Name="HealthCardNum" ControlID="txtHealthCard" PropertyName="Text" />
            <asp:ControlParameter Name="SIN" ControlID="txtSIN" PropertyName="Text" />
            <asp:ControlParameter Name="Password" ControlID="txtPatientPass" PropertyName="Text" />
            <asp:ControlParameter Name="Doctor" ControlID="listDoctor" PropertyName="SelectedValue" />
            <asp:ControlParameter Name="Status" ControlID="txtStatus" PropertyName="Text" />
        </InsertParameters>
        <DeleteParameters>
            <asp:SessionParameter SessionField="PatientID"  Name="PatientID" />
        </DeleteParameters>
          <UpdateParameters>
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[0].Text" Name="PatientID" Type="UInt32" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[1].Text" Name="PatientName" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[2].Text" Name="Address" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[3].Text" Name="PhoneNum" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[4].Text" Name="HealthCardNum" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[5].Text" Name="SIN" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[6].Text" Name="Password" Type="String" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[7].Text" Name="NumVisits" Type="UInt32" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[8].Text" Name="Doctor" Type="UInt32" />
            <asp:ControlParameter ControlID="patientGrid" PropertyName="SelectedRow.Cells[9].Text" Name="Status" Type="UInt32" />
        </UpdateParameters>
        </asp:SqlDataSource>
    <hr />
    <asp:GridView ID="Patients" runat="server" 
        DataSourceID="PatientData0" DataKeyNames="PatientID" 
        AutoGenerateSelectButton="True">
        <SelectedRowStyle BorderColor="Red" BorderStyle="Solid" />
    </asp:GridView>
    <asp:Button ID="Button2" runat="server" onclick="Button2_Click" 
        Text="View Patient Details" />
    <asp:SqlDataSource ID="PatientData0" runat="server" 
        ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
        SelectCommand="SELECT PatientID,PatientName,Address,PhoneNum,(SELECT COUNT(*) FROM visits as v WHERE v.PatientID=p.PatientID) as NumVisits,Doctor,Status FROM patients as p WHERE (PatientID in (Select PatientID FROM viewingrights WHERE EmployeeID=@empID))" 
        UpdateCommand="UPDATE patients SET PatientName=@PatientName, Address=@Address,PhoneNum=@PhoneNum,NumVisits=@NumVisits,Doctor=@Doctor,Status=@Status WHERE PatientID=@PatientID"
        DeleteCommand="DELETE FROM patients WHERE PatientID=@PatientID">
        <DeleteParameters>
            <asp:SessionParameter SessionField="Deleting" Name="PatientID" />
        </DeleteParameters>
        <SelectParameters>
            <asp:QueryStringParameter Name="empID" QueryStringField="empID" />
        </SelectParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="Patients" PropertyName="SelectedRow.Cells[0].Text" Name="PatientID" Type="UInt32" />
            <asp:ControlParameter ControlID="Patients" PropertyName="SelectedRow.Cells[1].Text" Name="PatientName" Type="String" />
            <asp:ControlParameter ControlID="Patients" PropertyName="SelectedRow.Cells[2].Text" Name="Address" Type="String" />
            <asp:ControlParameter ControlID="Patients" PropertyName="SelectedRow.Cells[3].Text" Name="PhoneNum" Type="String" />
            <asp:ControlParameter ControlID="Patients" PropertyName="SelectedRow.Cells[4].Text" Name="HealthCardNum" Type="String" />
            <asp:ControlParameter ControlID="Patients" PropertyName="SelectedRow.Cells[5].Text" Name="SIN" Type="String" />
            <asp:ControlParameter ControlID="Patients" PropertyName="SelectedRow.Cells[6].Text" Name="NumVisits" Type="UInt32" />
            <asp:ControlParameter ControlID="Patients" PropertyName="SelectedRow.Cells[7].Text" Name="Doctor" Type="UInt32" />
            <asp:ControlParameter ControlID="Patients" PropertyName="SelectedRow.Cells[8].Text" Name="Status" Type="UInt32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <br />
    </form>
<p class="style1">
        
        <input type="button" value="Back" name="ClickBack" onclick=(history.back())></p>
</body>
</html>
