<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ViewingRights.aspx.cs" Inherits="ViewingRights" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Patient Viewing Rights - HospitalDB</title>
</head>
<body>
    <form id="form1" runat="server">
    <asp:Label ID="Label1" runat="server"></asp:Label>
    <br />
    <asp:DropDownList ID="drList" runat="server" DataSourceID="drsource" 
        DataTextField="EmployeeName" DataValueField="EmployeeID">
    </asp:DropDownList>
    <asp:Button ID="btnAddView" runat="server" 
        Text="Add Doctor to Patient Viewing Rights" onclick="btnAddView_Click" />
    <br />
    <asp:GridView ID="viewrightsgrid" runat="server" DataSourceID="viewSource" 
        AutoGenerateDeleteButton="True" onrowdeleting="viewrightsgrid_RowDeleting" 
        onrowdeleted="viewrightsgrid_RowDeleted" 
        onrowcreated="viewrightsgrid_RowCreated" 
        onrowupdating="viewrightsgrid_RowUpdating">
    </asp:GridView>
    <div>
    
    <asp:SqlDataSource ID="viewSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
        SelectCommand="Select EmployeeID FROM viewingrights WHERE PatientID=@patID"
        DeleteCommand="DELETE FROM viewingrights Where EmployeeID=@empID and PatientID=@patID">
        <SelectParameters>
        <asp:QueryStringParameter Name="patID" QueryStringField="patID" />
        </SelectParameters>
        <DeleteParameters>
        <asp:SessionParameter Name="patID" SessionField="patID" />
        <asp:SessionParameter Name="empID" SessionField="empID" />
        </DeleteParameters>
        </asp:SqlDataSource>
    
        <asp:SqlDataSource ID="drsource" runat="server" 
            ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
            ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
            SelectCommand="SELECT EmployeeID, EmployeeName from employees where Job='Doctor' OR Job='Staff'">
            
            </asp:SqlDataSource>
            
    </div>
    </form>
</body>
</html>
