<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Admin.aspx.cs" Inherits="Default2" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>HospitalDB - Admin View</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        Admin Tools - Add/Edit/Remove Employeee<br />
        <br />
    
        <asp:TextBox ID="txtEmpName" runat="server">Employee Name</asp:TextBox>
        <asp:DropDownList ID="jobList" runat="server">
            <asp:ListItem>Doctor</asp:ListItem>
            <asp:ListItem>Legal</asp:ListItem>
            <asp:ListItem>Finance</asp:ListItem>
            <asp:ListItem>Staff</asp:ListItem>
        </asp:DropDownList>
        <asp:TextBox ID="txtEmpPass" runat="server">Employee Password</asp:TextBox>
        <asp:Button ID="btnAddEmp" runat="server" Text="Add New Employee" 
            onclick="btnAddEmp_Click" />
    
        <hr />
    
    </div>
    <asp:GridView ID="empGrid" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataSourceID="employeeData">
    </asp:GridView>
    <asp:SqlDataSource ID="employeeData" runat="server" 
        ConnectionString="<%$ ConnectionStrings:hospital_G004ConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:hospital_G004ConnectionString.ProviderName %>" 
        SelectCommand="SELECT * FROM EMPLOYEES" onupdated="employeeData_Updated"
        InsertCommand="INSERT INTO employees (EmployeeName, Job, Passwd) VALUES (@EmployeeName, @Job, @Passwd)">
        <InsertParameters>
            <asp:ControlParameter Name="EmployeeName" ControlID="txtEmpName" PropertyName="Text" />
            <asp:ControlParameter Name="Job" ControlID="jobList" PropertyName="SelectedValue" />
            <asp:ControlParameter Name="Passwd" ControlID="txtEmpPass" PropertyName="Text" />
        </InsertParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
