<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Doctor.aspx.cs" Inherits="Doctor" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>HospitalDB - Doctor View</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
    <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
    <p>
        <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
            Text="View Patients" />
    </p>
    <asp:GridView ID="Patients" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" onrowdeleting="Patients_RowDeleting" 
        onrowediting="Patients_RowEditing">
    </asp:GridView>
    </form>
</body>
</html>
